apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory-service
spec:
  dependsOn:
    - component:default/user:guest
    - component:user:guest
  type: service
  lifecycle: production
  owner: team-inventory
  providesApis:
    - inventory-api
  
